version: "2"
services:
    kafka:
        image: spotify/kafka
        hostname: kafka
        environment:
            - "TOPICS=author-topic"
            - "ADVERTISED_HOST=kafka"
            - "ADVERTISED_PORT=9092"
            - "ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092"
        ports:
            - "9092:9092"
            - "2181:2181"
        expose: 
            - "9092"
            - "2181"
    nats:
        image: nats:0.8.0
        entrypoint: "/gnatsd -D"
        expose:
        - "4222"
        ports:
        - "8222:8222"
        hostname: nats-server
    gateway:
        build: ./gateway
        ports:
            - "4000:4000"
        links: 
            - nats:nats-server
        depends_on:
            - author_read
            - author_write
    author_read:
        build: ./author-read
        links: 
            - nats:nats-server
            - kafka
        depends_on:
            - kafka
            - nats
    author_write:
        build: ./author-write
        links: 
            - nats:nats-server
            - kafka
        depends_on:
            - kafka
            - nats
